# -*- coding: utf-8 -*-
"""
Created on Sat Oct 21 18:25:11 2023

@author: ajult
"""

APP_FONT = ("Verdana", 10)
APP_HEADINGS_FONT = ("Verdana", 16)
APP_FONT_COLOUR = "#000"

MENU_FONT_COLOUR = "#000"
TEST_BACKGROUND = "#CACACA"
MENU_BACKGROUND = "#D8E1E9"


MENU_LABEL_FONT_COLOUR = "#0A369D"
MENU_LABEL_FONT = ("Verdana", 12)

BUTTON_BACKGROUND = "#0A369D"
BUTTON_FORGROUND = "#fff"

MAIN_BACKGROUND = "#C4CBCA"
MAIN_FONT_COLOUR="#0A369D"